---
title: "Bankrupt"
author: "Qianyu Yang and Tom Davis"
date: "2023-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Project Proposal
For our proposal we will be doing the following:
- Using a bankruptcy data set 
- Asking the question whether or not these banks will go bankrupt
- Preliminary explorations are below
- Link to repository: https://github.com/rtomdavs/TO628

```{r}
bankruptcy <- read.csv("bankruptcy.csv")
summary(bankruptcy)
bankruptcy$Net.worth.Assets <- NULL
bankruptcy$Current.Liability.to.Liability <- NULL
bankruptcy$Current.Liability.to.Equity <- NULL
bankruptcy$Net.Income.Flag <- NULL
str(bankruptcy)
```

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

bankmm <- as.data.frame(model.matrix(~.-1,bankruptcy))
str(bankmm)

# Randomize the rows in the data (shuffling the rows)
set.seed(12345)
bank_random <- bankmm[sample(nrow(bankmm)),]

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything 
bank_norm <- as.data.frame(lapply(bank_random, normalize))

```

```{r}
# Selects 10000 random rows for test data
set.seed(12345)
test_set <- sample(1:nrow(bank_norm), 3000) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 

# Create a train set and test set
#First the predictors - all columns except the yyes column
bank_train <- bank_norm[-test_set, -match("Bankrupt.",names(bank_norm))]
bank_test <- bank_norm[test_set, -match("Bankrupt.",names(bank_norm))]

#Now the response (aka Labels) - only the yyes column
bank_train_labels <- bank_norm[-test_set, "Bankrupt."]
bank_test_labels <- bank_norm[test_set, "Bankrupt."]

```

```{r}
bank_train_new<- bank_norm[-test_set, ]
bank_test_new<- bank_norm[test_set, ]
library(neuralnet)
simplemodel <- neuralnet(Bankrupt. ~ ., data = bank_train_new, hidden = 1)
plot(simplemodel)
```

```{r}
simplepred <- predict(simplemodel,bank_test_new)
summary(simplepred)
simplebin <- ifelse(simplepred >= 0.5, 1, 0)
library(caret)
confusionMatrix(as.factor(simplebin),as.factor(bank_test_new$Bankrupt.), positive = "1")

```

## KNN
```{r}
library(class)
bank_model <- knn(bank_train,bank_test, bank_train_labels, k = 50)
confusionMatrix(as.factor(bank_model), as.factor(bank_test_labels), positive = "1")
```