---
title: "College Dropout Prediction"
author: "The Kumar Kids"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    theme: spacelab
    highlight: zenburn
date: "2023-04-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial Model Building and Testing

## Reading and Cleaning
```{r}
#Reading in the dataset
drops <- read.csv("dataset.csv")

#Converting appropriate columns into factor
factorcols <- c("Marital.status", "Application.mode", "Daytime.evening.attendance", "Course", "Previous.qualification",
          "Nacionality", "Mother.s.qualification", "Father.s.qualification", "Mother.s.occupation",
          "Father.s.occupation", "Displaced", "Educational.special.needs", "Debtor", "Tuition.fees.up.to.date",
          "Gender", "Scholarship.holder", "International")


drops[factorcols] <- lapply(drops[factorcols], factor)
str(drops)

#Removing the enrolled students, for later prediction
nonenr <- subset(drops, drops$Target != "Enrolled")
str(nonenr)

#Factorizing target
nonenr$Target <- as.factor(nonenr$Target)
str(nonenr)

#Converting to Model Matrix
dummydrop <- as.data.frame(model.matrix(~., nonenr))


#summary(nonenr)
```

# Initial Loading and Logistic Regression
## Testing and Training Sets
```{r}
set.seed(12345)
trainrows <- sample(nrow(dummydrop), 0.8*nrow(dummydrop))

droptrain <- dummydrop[trainrows, ]
droptest <- dummydrop[-trainrows, ]
```

## Building Logistic Model
```{r}
logmod <- lm(TargetGraduate ~., data = droptrain)
```

## Testing Logistic Model
```{r}
library(caret)

Logpred <- predict(logmod, droptest)
pblog <- ifelse(Logpred >= 0.5, 1, 0)
confusionMatrix(as.factor(pblog), as.factor(droptest$Target), positive = "1")

summary(droptest)
```

# Creating KNN model